Mentor.delete_all
Mentee.delete_all
Pairing.delete_all
# ActiveRecord::Base.connection.execute("DELETE from sqlite_sequence where name = 'mentors'")
# ActiveRecord::Base.connection.execute("DELETE from sqlite_sequence where name = 'mentees'")
# ActiveRecord::Base.connection.execute("DELETE from sqlite_sequence where name = 'pairings'")

# Mentor Seeds
steven = Mentor.create(full_name: "Steven Kandow", age: 34, gender: "male", favorite_hobby: "basket-weaving", location: "middle-of-nowhere")
john = Mentor.create(full_name: "John Loberger", age: 23, gender: "male", favorite_hobby: "video games", location: "Middle Earth")
ash = Mentor.create(full_name: "Ashley Ketchum", age: 26, gender: "female", favorite_hobby: "video games", location: "Japan")
greg = Mentor.create(full_name: "Greg Grunberg", age: 49, gender: "male", favorite_hobby: "video games", location: "Los Angeles")
lebron = Mentor.create(full_name: "LeBron James", age: 34, gender: "male", favorite_hobby: "basketball", location: "Los Angeles")
walter_white = Mentor.create(full_name: "Bryan Cranston", age: 52, gender: "male", favorite_hobby: "acting", location: "Los Angeles")
spider_man = Mentor.create(full_name: "Peter Parker", age: 25, gender: "male", favorite_hobby: "photography", location: "New York")
serena = Mentor.create(full_name: "Serena Williams", age: 37, gender: "female", favorite_hobby: "tennis", location: "San Diego")
rafa = Mentor.create(full_name: "Rafael Nadal", age: 38, gender: "male", favorite_hobby: "tennis", location: "Barcelona")
cristiano = Mentor.create(full_name: "Cristiano Ronaldo", age: 39, gender: "male", favorite_hobby: "soccer", location: "Madrid")
vader = Mentor.create(full_name: "Darth Vader", age: 44, gender: "male", favorite_hobby: "the Force", location: "Death Star")
kenobi = Mentor.create(full_name: "Ben Kenobi", age: 56, gender: "male", favorite_hobby: "the Force", location: "Tatooine")
ashoka = Mentor.create(full_name: "Ashoka Tano", age: 28, gender: "female", favorite_hobby: "the Force", location: "middle-of-nowhere")
yoda = Mentor.create(full_name: "Yoda", age: 900, gender: "male", favorite_hobby: "the Force", location: "Dagobah")
meryl = Mentor.create(full_name: "Meryl Streep", age: 67, gender: "female", favorite_hobby: "acting", location: "Los Angeles")
carpenter = Mentor.create(full_name: "John Carpenter", age: 73, gender: "male", favorite_hobby: "scaring", location: "Los Angeles")
uncharted = Mentor.create(full_name: "Nathan Drake", age: 29, gender: "male", favorite_hobby: "video games", location: "unknown")
durant = Mentor.create(full_name: "Kevin Durant", age: 40, gender: "male", favorite_hobby: "basketball", location: "Los Angeles")
duke = Mentor.create(full_name: "Duke Greene", age: 33, gender: "male", favorite_hobby: "coding", location: "Chicago")
ramsay = Mentor.create(full_name: "Gordon Ramsay", age: 61, gender: "male", favorite_hobby: "cooking", location: "London")
nick = Mentor.create(full_name: "Nick Moore", age: 33, gender: "male", favorite_hobby: "coding", location: "Chicago")
barry = Mentor.create(full_name: "Barry Allen", age: 28, gender: "male", favorite_hobby: "running", location: "Central City")
lee = Mentor.create(full_name: "Harper Lee", age: 78, gender: "female", favorite_hobby: "writing", location: "Montgomery")
jo = Mentor.create(full_name: "Jo Ann", age: 82, gender: "female", favorite_hobby: "sewing", location: "Topeka")
emily = Mentor.create(full_name: "Emily Dickinson", age: 35, gender: "female", favorite_hobby: "writing", location: "Kansas City")
martha = Mentor.create(full_name: "Martha Stewart", age: 73, gender: "female", favorite_hobby: "sewing", location: "Los Angeles")
link = Mentor.create(full_name: "Link Hero", age: 18, gender: "male", favorite_hobby: "archery", location: "Hyrule")
tyrion = Mentor.create(full_name: "Tyrion Lannister", age: 33, gender: "male", favorite_hobby: "knowing things", location: "Kings Landing")
gustavo = Mentor.create(full_name: "Gustavo Dudamel", age: 56, gender: "male", favorite_hobby: "music", location: "Los Angeles")
marin = Mentor.create(full_name: "Marin Alsop", age: 64, gender: "female", favorite_hobby: "music", location: "Los Angeles")
gronk = Mentor.create(full_name: "Rob Gronkowski", age: 31, gender: "male", favorite_hobby: "football", location: "Tampa")
peyton = Mentor.create(full_name: "Peyton Manning", age: 46, gender: "male", favorite_hobby: "football", location: "Denver")
kimmel = Mentor.create(full_name: "Jimmy Kimmel", age: 51, gender: "male", favorite_hobby: "comedy", location: "Los Angeles")
fallon = Mentor.create(full_name: "Jimmy Fallon", age: 48, gender: "male", favorite_hobby: "comedy", location: "Los Angeles")
dumbledore = Mentor.create(full_name: "Albus Dumbledore", age: 88, gender: "male", favorite_hobby: "magic", location: "Hogwarts")
gandalf = Mentor.create(full_name: "Gandalf White", age: 5000, gender: "male", favorite_hobby: "magic", location: "Middle Earth")

# Mentee Seeds
mike = Mentee.create(full_name: "Mike Wyzowski", age: 17, gender: "male", favorite_hobby: "basket-weaving", location: "Middle Earth", guardian_contact: "Randall Scary_monster")
sully = Mentee.create(full_name: "Sully Bluemonster", age: 24, gender: "male", favorite_hobby: "scaring", location: "middle-of-nowhere")
pew_dee_pie = Mentee.create(full_name: "Pew Pie", age: 25, gender: "male", favorite_hobby: "video games", location: "Middle Earth")
coco = Mentee.create(full_name: "Coco Gauff", age: 16, gender: "female", favorite_hobby: "tennis", location: "Los Angeles", guardian_contact: "Corey Gauff")
paul = Mentee.create(full_name: "Paul Lavender", age: 32, gender: "male", favorite_hobby: "music", location: "Portland")
teevee = Mentee.create(full_name: "Mike Teevee", age: 12, gender: "male", favorite_hobby: "video games", location: "Middle Earth", guardian_contact: "Ellen Teevee")
cooper = Mentee.create(full_name: "Sheldon Cooper", age: 35, gender: "male", favorite_hobby: "role-playing games", location: "Pasadena")
luke = Mentee.create(full_name: "Luke Skywalker", age: 18, gender: "male", favorite_hobby: "the Force", location: "Tatooine")
gary = Mentee.create(full_name: "Gary Oak", age: 10, gender: "male", favorite_hobby: "video games", location: "Pallet Town", guardian_contact: "Sam Oak")
bugs = Mentee.create(full_name: "Bugs Bunny", age: 60, gender: "male", favorite_hobby: "basketball", location: "Looney Tune Land")
croft = Mentee.create(full_name: "Lara Croft", age: 24, gender: "female", favorite_hobby: "video games", location: "unknown")
rey = Mentee.create(full_name: "Rey Palpatine", age: 22, gender: "female", favorite_hobby: "the Force", location: "Jakku")
sue = Mentee.create(full_name: "Sue Belanger", age: 60, gender: "female", favorite_hobby: "sewing", location: "Detroit")
wakka = Mentee.create(full_name: "Pac Man", age: 47, gender: "male", favorite_hobby: "coding", location: "Arcadeland")
forrest = Mentee.create(full_name: "Forrest Gump", age: 13, gender: "male", favorite_hobby: "running", location: "Greenbow", guardian_contact: "Sally Field")
cole = Mentee.create(full_name: "Cole Sprouse", age: 27, gender: "male", favorite_hobby: "acting", location: "Riverdale")
dylan = Mentee.create(full_name: "Dylan Sprouse", age: 27, gender: "male", favorite_hobby: "acting", location: "Yozura")
mario = Mentee.create(full_name: "Mario Mario", age: 25, gender: "male", favorite_hobby: "soccer", location: "Mushroom Kingdom")
luigi= Mentee.create(full_name: "Luigi Mario", age: 25, gender: "male", favorite_hobby: "tennis", location: "Mushroom Kingdom")
peach = Mentee.create(full_name: "Princess Peach", age: 22, gender: "female", favorite_hobby: "tennis", location: "Mushroom Kingdom")
cake = Mentee.create(full_name: "Patty Cake", age: 12, gender: "female", favorite_hobby: "cooking", location: "Cleveland", guardian_contact: "Bundt Cake")
snap = Mentee.create(full_name: "Todd Snap", age: 11, gender: "male", favorite_hobby: "photography", location: "Pallet Town", guardian_contact: "Sam Oak")
russell = Mentee.create(full_name: "Russell Fredrickson", age: 12, gender: "male", favorite_hobby: "basket-weaving", location: "Paradise Falls", guardian_contact: "Carl Fredrickson")
jake = Mentee.create(full_name: "Jake Marcionette", age: 12, gender: "male", favorite_hobby: "writing", location: "New York", guardian_contact: "Mike Marcionette")
rudy = Mentee.create(full_name: "Rudy Ruttiger", age: 18, gender: "male", favorite_hobby: "football", location: "South Bend")
osment = Mentee.create(full_name: "Haley Joel Osment", age: 12, gender: "male", favorite_hobby: "comedy", location: "Nostalgia", guardian_contact: "Bruce Willis")
samwise = Mentee.create(full_name: "Samwise Gamgee", age: 78, gender: "male", favorite_hobby: "gardening", location: "Middle Earth")
katniss = Mentee.create(full_name: "Katniss Everdeen", age: 18, gender: "female", favorite_hobby: "archery", location: "District 12")
peeta = Mentee.create(full_name: "Peeta Mellark", age: 18, gender: "male", favorite_hobby: "gardening", location: "District 12")
harry = Mentee.create(full_name: "Harry Potter", age: 12, gender: "male", favorite_hobby: "magic", location: "Little Whinging", guardian_contact: "Vernon Dursley")
jess = Mentee.create(full_name: "Jess Bhamra", age: 18, gender: "female", favorite_hobby: "soccer", location: "London")
jules = Mentee.create(full_name: "Jules Paxton", age: 18, gender: "female", favorite_hobby: "soccer", location: "London")
jigsaw = Mentee.create(full_name: "John Kramer", age: 68, gender: "male", favorite_hobby: "scaring", location: "Los Angeles")

# Pairing Seeds
pairing_one = Pairing.create(mentor: serena, mentee: coco, status: "Pending")
pairing_two = Pairing.create(mentor: steven, mentee: mike, status: "Pending")
pairing_three = Pairing.create(mentor: john, mentee: pew_dee_pie, status: "Pending")
pairing_four = Pairing.create(mentor: john, mentee: gary, status: "Pending")
pairing_five = Pairing.create(mentor: dumbledore, mentee: harry, status: "Pending")
pairing_six = Pairing.create(mentor: duke, mentee: wakka, status: "Pending")
pairing_seven = Pairing.create(mentor: rafa, mentee: luigi, status: "Pending")
pairing_eight = Pairing.create(mentor: martha, mentee: sue, status: "Pending")